// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyJvyWAgwCS1FAN_7xpvU5JZ5N0XjLdp8',
    appId: '1:365993871491:web:41dc28896cafbe18c173b6',
    messagingSenderId: '365993871491',
    projectId: 'urban-green-mapper-71d23',
    authDomain: 'urban-green-mapper-71d23.firebaseapp.com',
    storageBucket: 'urban-green-mapper-71d23.firebasestorage.app',
    measurementId: 'G-2XHBN0EL0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAO8mq9IdeOOqPFyw2NpvrHFajdxB7sfA',
    appId: '1:365993871491:android:6fbdab978b4fc356c173b6',
    messagingSenderId: '365993871491',
    projectId: 'urban-green-mapper-71d23',
    storageBucket: 'urban-green-mapper-71d23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5GXYpyXOGSbaq-nmk_gNd_RpbDf8qIJ8',
    appId: '1:365993871491:ios:1c51e93af174af92c173b6',
    messagingSenderId: '365993871491',
    projectId: 'urban-green-mapper-71d23',
    storageBucket: 'urban-green-mapper-71d23.firebasestorage.app',
    iosClientId: '365993871491-jn24evhd66dukn7eqogf1qov4s06ktir.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanGreenMapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5GXYpyXOGSbaq-nmk_gNd_RpbDf8qIJ8',
    appId: '1:365993871491:ios:1c51e93af174af92c173b6',
    messagingSenderId: '365993871491',
    projectId: 'urban-green-mapper-71d23',
    storageBucket: 'urban-green-mapper-71d23.firebasestorage.app',
    iosClientId: '365993871491-jn24evhd66dukn7eqogf1qov4s06ktir.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanGreenMapper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyJvyWAgwCS1FAN_7xpvU5JZ5N0XjLdp8',
    appId: '1:365993871491:web:26aacbbd8b9e983bc173b6',
    messagingSenderId: '365993871491',
    projectId: 'urban-green-mapper-71d23',
    authDomain: 'urban-green-mapper-71d23.firebaseapp.com',
    storageBucket: 'urban-green-mapper-71d23.firebasestorage.app',
    measurementId: 'G-GTE4G4R3NC',
  );
}
